version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: myapp-mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myapp
        - MYSQL_USER=myapp
        - MYSQL_PASSWORD=myapp
    ports:
      - 8106:3306
    volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - myappnetwork
  cakephp:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: myapp-php-fpm
    volumes:
        - myappvolume:/var/www/myapp
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    networks:
      - myappnetwork
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: myapp-nginx
    volumes:
        - myappvolume:/var/www/myapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    depends_on:
      - cakephp
    networks:
      - myappnetwork
  react:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: myapp-react
    ports:
      - "5004:8080"
    networks:
      - myappnetwork
networks:
  myappnetwork:
volumes:
  myappvolume: