FROM bitnami/php-fpm:7.1

RUN apt-get update

RUN apt-get install git -y

RUN apt-get update \
    && apt-get -y --no-install-recommends install php7.1-mysql php7.1-intl php7.1-mbstring php7.1-sqlite3\
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

WORKDIR "/var/www/myapp"

RUN git clone https://github.com/muhammedfatih/MailboxSample.BackEnd.CakePhp.git .

RUN COMPOSER_MEMORY_LIMIT=-1 composer install